### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by NT-Christ** [danfoster/solis#1]
anyio = "^4.4.0"

Traceback (most recent call last):
  File "/home/ubuntu/solaris/solis/.venv/bin/solis", line 3, in <module>
    from solis.cli import main
  File "/home/ubuntu/solaris/solis/src/solis/cli.py", line 2, in <module>
    import asyncclick as click
  File "/home/ubuntu/solaris/solis/.venv/lib/python3.12/site-packages/asyncclick/__init__.py", line 7, in <module>
    from .core import Argument as Argument
  File "/home/ubuntu/solaris/solis/.venv/lib/python3.12/site-packages/asyncclick/core.py", line 1, in <module>
    import anyio
ModuleNotFoundError: No module named 'anyio'

**Comment by danfoster** [comment]
How did you install it?

In a standard virtualenv It pulled in `anyio` with a `pip install` on `3.10`

```
$ pip3 install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/dan/git/zem/solis
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting asyncclick<9.0.0.0,>=8.1.3.4
  Downloading asyncclick-8.1.7.2-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 KB 3.6 MB/s eta 0:00:00
Collecting click<9.0.0,>=8.1.3
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 KB 7.9 MB/s eta 0:00:00
Collecting zem-pysolarmanv5<3.0.0,>=2.5.0rc2
  Downloading zem_pysolarmanv5-2.5.0rc2-py3-none-any.whl (13 kB)
Collecting anyio
  Downloading anyio-4.4.0-py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 KB 9.6 MB/s eta 0:00:00
Collecting umodbus
  Downloading uModbus-1.0.4-py2.py3-none-any.whl (31 kB)
Collecting typing-extensions>=4.1
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting sniffio>=1.1
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting idna>=2.8
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 KB 9.3 MB/s eta 0:00:00
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Collecting pyserial~=3.4
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 KB 11.1 MB/s eta 0:00:00
Building wheels for collected packages: solis
  Building editable for solis (pyproject.toml) ... done
  Created wheel for solis: filename=solis-0.1.1-py3-none-any.whl size=2194 sha256=7aca6b798b12030409d87fa4c696d3153a85ffda527e7836dd8f67259670a124
  Stored in directory: /tmp/pip-ephem-wheel-cache-5bxfw689/wheels/e1/06/83/8c229ea62286de51453d4ead3ce3fa992b21eec524a1670055
Successfully built solis
Installing collected packages: pyserial, umodbus, typing-extensions, sniffio, idna, exceptiongroup, click, zem-pysolarmanv5, anyio, asyncclick, solis
Successfully installed anyio-4.4.0 asyncclick-8.1.7.2 click-8.1.7 exceptiongroup-1.2.1 idna-3.7 pyserial-3.5 sniffio-1.3.1 solis-0.1.1 typing-extensions-4.12.2 umodbus-1.0.4 zem-pysolarmanv5-2.5.0rc2
```
